--Demo
/*
Market adında bir veritabanı oluşturunuz....

Müşteri Tablosu oluşturan bir sql sorgusu
[musteriID,ad,soyad]

Urun tablosu oluşturan sql sorgusu
[urunID,urunAd,urunFiyat]

Satis tablosu oluşturan sql sorgusu
[satisID,musteriId,urunId,Miktar]

Aşağıdaki sorgulara cevap veren view,fonksiyon,procedure oluşturulması
-Satış işlemi yapan Store Procedure
-Toplam Satış Sayısını getiren view
-Toplam Satış Tutarı
-En çok satış yapan müşteri
-En çok satış yapan müşteri
*/
